// <auto-generated />
using System;
using CourseHub.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourseHub.Migrations
{
    [DbContext(typeof(CourseHubContext))]
    [Migration("20251030101016_Edit Migration CreateDataBase")]
    partial class EditMigrationCreateDataBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourseHub.Models.CourseDB.Course", b =>
                {
                    b.Property<int>("CourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseID"));

                    b.Property<string>("CourseDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseDurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("CourseImagePath")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("CourseIsDelete")
                        .HasColumnType("bit");

                    b.Property<int>("CourseLevel")
                        .HasColumnType("int");

                    b.Property<decimal>("CoursePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CoursePublishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CourseSlug")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CourseTitle")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("CourseID");

                    b.HasIndex("CourseSlug")
                        .IsUnique()
                        .HasDatabaseName("IX_Course_CourseSlug");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("CourseHub.Models.CourseHubDB.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategoryParentID")
                        .HasColumnType("int");

                    b.Property<string>("CategorySlug")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CategoryID");

                    b.HasIndex("CategoryParentID");

                    b.HasIndex("CategorySlug")
                        .IsUnique()
                        .HasDatabaseName("IX_Cours_CategorySlug");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("CourseHub.Models.CourseHubDB.Course_Category", b =>
                {
                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.HasKey("CourseID", "CategoryID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Course_Categories");
                });

            modelBuilder.Entity("CourseHub.Models.CourseHubDB.Course_Teacher", b =>
                {
                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<int>("TeacherID")
                        .HasColumnType("int");

                    b.HasKey("CourseID", "TeacherID");

                    b.HasIndex("TeacherID");

                    b.ToTable("Course_Teachers");
                });

            modelBuilder.Entity("CourseHub.Models.CourseHubDB.Teacher", b =>
                {
                    b.Property<int>("TeacherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherID"));

                    b.Property<string>("TeacherBio")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TeacherFullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("TeacherID");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("CourseHub.Models.CourseHubDB.Category", b =>
                {
                    b.HasOne("CourseHub.Models.CourseHubDB.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryParentID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CourseHub.Models.CourseHubDB.Course_Category", b =>
                {
                    b.HasOne("CourseHub.Models.CourseHubDB.Category", "Category")
                        .WithMany("Course_Categories")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseHub.Models.CourseDB.Course", "Course")
                        .WithMany("Course_Categories")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("CourseHub.Models.CourseHubDB.Course_Teacher", b =>
                {
                    b.HasOne("CourseHub.Models.CourseDB.Course", "Course")
                        .WithMany("Course_Teachers")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseHub.Models.CourseHubDB.Teacher", "Teacher")
                        .WithMany("Course_Teachers")
                        .HasForeignKey("TeacherID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("CourseHub.Models.CourseDB.Course", b =>
                {
                    b.Navigation("Course_Categories");

                    b.Navigation("Course_Teachers");
                });

            modelBuilder.Entity("CourseHub.Models.CourseHubDB.Category", b =>
                {
                    b.Navigation("Course_Categories");
                });

            modelBuilder.Entity("CourseHub.Models.CourseHubDB.Teacher", b =>
                {
                    b.Navigation("Course_Teachers");
                });
#pragma warning restore 612, 618
        }
    }
}
